USE sales
GO

USE sales
GO

CREATE TABLE DataRaw.SalesData (
	[OrderID]                   [varchar](4096) NOT NULL,
	[OrderDate]                 [varchar](4096) NULL,
	[OrderRequiredDate]         [varchar](4096) NULL,
	[OrderShippedDate]          [varchar](4096) NULL,
	[OrderShipVia]              [varchar](4096) NULL,
	[OrderFreight]              [varchar](4096) NULL,
	[OrderShipName]             [varchar](4096) NULL,
	[OrderShipAddress]          [varchar](4096) NULL,
	[OrderShipCity]             [varchar](4096) NULL,
	[OrderShipRegion]           [varchar](4096) NULL,
	[OrderShipPostalCode]       [varchar](4096) NULL,
	[OrderShipCountry]          [varchar](4096) NULL,
	[CustomerID]                [varchar](4096) NOT NULL,
	[CustCompanyName]           [varchar](4096) NULL,
	[CustContactName]           [varchar](4096) NULL,
	[CustContactTitle]          [varchar](4096) NULL,
	[CustAddress]               [varchar](4096) NULL,
	[CustCity]                  [varchar](4096) NULL,
	[CustRegion]                [varchar](4096) NULL,
	[CustPostalCode]            [varchar](4096) NULL,
	[CustCountry]               [varchar](4096) NULL,
	[CustPhone]                 [varchar](4096) NULL,
	[CustFax]                   [varchar](4096) NULL,
	[EmployeeID]                [varchar](4096) NOT NULL,
	[EmployeeLastName]          [varchar](4096) NULL,
	[EmployeeFirstName]         [varchar](4096) NULL,
	[EmployeeTitle]             [varchar](4096) NULL,
	[EmployeeTitleOfCourtesy]   [varchar](4096) NULL,
	[EmployeeBirthDate]         [varchar](4096) NULL,
	[EmployeeHireDate]          [varchar](4096) NULL,
	[EmployeeAddress]           [varchar](4096) NULL,
	[EmployeeCity]              [varchar](4096) NULL,
	[EmployeeRegion]            [varchar](4096) NULL,
	[EmployeePostalCode]        [varchar](4096) NULL,
	[EmployeeCountry]           [varchar](4096) NULL,
	[EmployeeHomePhone]         [varchar](4096) NULL,
	[EmployeeExtension]         [varchar](4096) NULL,
	[EmployeeNotes]             [varchar](4096) NULL,
	[EmployeeReportsTo]         [varchar](4096) NULL,
	[UnitPrice]                 [varchar](4096)  NULL,
	[Quantity]                  [varchar](4096)  NULL,
	[Discount]                  [varchar](4096)  NULL,
	[ProductID]                 [varchar](4096) NOT NULL,
	[ProductName]               [varchar](4096) NULL,
	[ProductSupplierID]         [varchar](4096) NULL,
	[ProductQuantityPerUnit]    [varchar](4096) NULL,
	[ProductUnitPrice]          [varchar](4096) NULL,
	[ProductUnitsInStock]       [varchar](4096) NULL,
	[ProductUnitsOnOrder]       [varchar](4096) NULL,
	[ProductReorderLevel]       [varchar](4096) NULL,
	[ProductDiscontinued]       [varchar](4096) NULL,
	[SupplierID]                [varchar](4096) NOT NULL,
	[SupplierCompanyName]       [varchar](4096) NULL,
	[SupplierContactName]       [varchar](4096) NULL,
	[SupplierContactTitle]      [varchar](4096) NULL,
	[SupplierAddress]           [varchar](4096) NULL,
	[SupplierCity]              [varchar](4096) NULL,
	[SupplierRegion]            [varchar](4096) NULL,
	[SupplierPostalCode]        [varchar](4096) NULL,
	[SupplierCountry]           [varchar](4096) NULL,
	[SupplierPhone]             [varchar](4096) NULL,
	[SupplierFax]               [varchar](4096) NULL,
	[CategoryID]                [varchar](4096) NOT NULL,
	[CategoryName]              [varchar](4096) NULL,
	[Description]               [varchar](4096) NULL
)
GO